server:
  port: 8080

spring:
  datasource:
     url: jdbc:mysql://10.37.251.224:3311/qding_weixin_platform
     username: qd
     password: jsEDtBU8
     driver-class-name: com.mysql.jdbc.Driver


## 配置获取api docs json数据的请求路径 ，默认为/v2/api-docs：
springfox:
  documentation:
    swagger:
      v2:
        host: www.abc.com
        path: /api
